import uuid
from typing import Protocol

from app.infrastructure.db.models import TimetableSlot


class TimetableSlotRepository(Protocol):
    async def list_for_course(self, course_id: uuid.UUID) -> list[TimetableSlot]: ...
    async def get_by_id(self, slot_id: uuid.UUID) -> TimetableSlot | None: ...
    async def add(self, slot: TimetableSlot) -> None: ...
    async def delete(self, slot: TimetableSlot) -> None: ...
