import uuid
from typing import Protocol

from app.infrastructure.db.models import CourseLecturer, Lecturer


class LecturerRepository(Protocol):
    async def list_all(self) -> list[Lecturer]: ...
    async def get_by_id(self, lecturer_id: uuid.UUID) -> Lecturer | None: ...
    async def add(self, lecturer: Lecturer) -> None: ...
    async def delete(self, lecturer: Lecturer) -> None: ...


class CourseLecturerRepository(Protocol):
    async def list_for_lecturer(self, lecturer_id: uuid.UUID) -> list[CourseLecturer]: ...
    async def list_for_course(self, course_id: uuid.UUID) -> list[CourseLecturer]: ...
    async def get(self, course_id: uuid.UUID, lecturer_id: uuid.UUID) -> CourseLecturer | None: ...
    async def add(self, link: CourseLecturer) -> None: ...
    async def delete(self, link: CourseLecturer) -> None: ...
