"""initial schema

Revision ID: 8bbc33ee90c8
Revises: 
Create Date: 2026-08-05 11:18:40.600722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bbc33ee90c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('COURSE', 'LECTURER', 'TIMETABLE_SLOT', 'CLASS_SESSION', 'REMINDER', 'ANNOUNCEMENT', name='audit_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'LECTURER', 'COURSE_REP', name='audit_actor'), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_contact_method', sa.Enum('EMAIL', 'WHATSAPP', name='contact_method'), nullable=False),
    sa.Column('fallback_contact_method', sa.Enum('EMAIL', 'WHATSAPP', name='contact_method'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('semesters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='course_status'), nullable=False),
    sa.Column('announcement_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'code', name='uq_course_semester_code')
    )
    op.create_table('calendar_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_lecturers',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'lecturer_id')
    )
    op.create_table('timetable_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', name='class_mode'), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('response_deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('fallback_contact_method_override', sa.Enum('EMAIL', 'WHATSAPP', name='contact_method'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('timetable_slot_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start_time', sa.Time(), nullable=False),
    sa.Column('scheduled_end_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', name='class_mode'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'REMINDER_SENT', 'PENDING_REVIEW', 'RESOLVED', 'UNRESOLVED', 'ANNOUNCED', name='session_status'), nullable=False),
    sa.Column('outcome', sa.Enum('CONFIRMED', 'CANCELLED', 'DELAYED', 'RELOCATED', 'ONLINE', 'UNRESOLVED', name='session_outcome'), nullable=True),
    sa.Column('final_start_time', sa.Time(), nullable=True),
    sa.Column('final_venue', sa.String(length=255), nullable=True),
    sa.Column('final_mode', sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', name='class_mode'), nullable=True),
    sa.Column('resolution_source', sa.Enum('PENDING', 'LECTURER_RESPONSE', 'MANUAL_OVERRIDE', 'NO_RESPONSE_FALLBACK', name='resolution_source'), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['timetable_slot_id'], ['timetable_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_slot_id', 'session_date', name='uq_slot_session_date')
    )
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_session_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', name='notification_channel_type'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='announcement_status'), nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_session_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', name='notification_channel_type'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outbound_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'RESPONDED', 'EXPIRED', 'CANCELLED', name='reminder_status'), nullable=False),
    sa.Column('apscheduler_job_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturer_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('class_session_id', sa.UUID(), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('cleaned_message', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_status', sa.Enum('CONFIRMED', 'CANCELLED', 'DELAYED', 'RELOCATED', 'ONLINE', 'UNCLEAR', name='ai_interpreted_status'), nullable=True),
    sa.Column('ai_new_time', sa.Time(), nullable=True),
    sa.Column('ai_new_venue', sa.String(length=255), nullable=True),
    sa.Column('ai_new_mode', sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', name='class_mode'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturer_responses')
    op.drop_table('reminders')
    op.drop_table('announcements')
    op.drop_table('class_sessions')
    op.drop_table('timetable_slots')
    op.drop_table('course_lecturers')
    op.drop_table('calendar_exceptions')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('semesters')
    op.drop_table('lecturers')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
